name: Deploy Orchestrator

on:
  push:
    tags:
      - 'deploy-*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  PROJECT_ID: echovaeris
  REGION: us-central1
  SERVICE_NAME: nova-orchestrator
  SERVICE_ACCOUNT: orchestrator-nova-sa@echovaeris.iam.gserviceaccount.com
  WI_POOL: projects/965158979432/locations/global/workloadIdentityPools/github-actions-pool
  GITHUB_SA: github-actions-sa@echovaeris.iam.gserviceaccount.com

jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --region ${{ env.REGION }} \
            --service-account ${{ env.SERVICE_ACCOUNT }} \
            --platform managed \
            --allow-unauthenticated \
            --add-cloudsql-instances echovaeris:us-central1:orch-pg \
            --set-env-vars "PROJECT_ID=${{ env.PROJECT_ID }},REGION=${{ env.REGION }}"
      
      - name: Get Service URL
        id: get-url
        run: |
          URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --format='value(status.url)')
          echo "service_url=$URL" >> $GITHUB_OUTPUT
          echo "Deployed to: $URL"
      
      - name: Run Combined Proof
        run: |
          echo "Running Combined Proof at ${{ steps.get-url.outputs.service_url }}"
          curl -X POST "${{ steps.get-url.outputs.service_url }}/proof" \
            -H "Content-Type: application/json" \
            -d '{
              "task": "COMBINED_PROOF_RUN",
              "agent": "Agent Builder",
              "deployment": "GitHub Actions",
              "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
            }' | tee combined_proof.json
          
          # Upload proof to GCS
          gsutil cp combined_proof.json gs://orch-artifacts/receipts/github_actions_proof_$(date +%Y%m%d_%H%M%S).json
      
      - name: Upload Proof Artifact
        uses: actions/upload-artifact@v3
        with:
          name: combined-proof
          path: combined_proof.json

  verify-deployment:
    needs: deploy-cloud-run
    runs-on: ubuntu-latest
    steps:
      - name: Download Proof
        uses: actions/download-artifact@v3
        with:
          name: combined-proof
      
      - name: Verify Proof Contents
        run: |
          echo "Verifying Combined Proof..."
          cat combined_proof.json | jq '.'
          
          # Check for required fields
          jq -e '.run_id' combined_proof.json
          jq -e '.receipts.cloud_sql.event_id' combined_proof.json
          jq -e '.receipts.gcs.artifact_path' combined_proof.json
          
          echo "✅ Deployment verified with receipts!"